package com.iut.banque.test.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.assertTrue;

import java.util.*;

public class TestConnexionAdminValide {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src\\test\\resources\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testConnectionLoginOk() {
        driver.get("http://localhost:8080/_00_ASBank2023_war_exploded/logout.action");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.linkText("Page de Login")).click();
        driver.get("http://localhost:8080/_00_ASBank2023_war_exploded/redirectionLogin.action");
        driver.findElement(By.xpath("//form[@id='controller_Connect_login_action']/table/tbody/tr")).click();
        driver.findElement(By.id("controller_Connect_login_action_userCde")).click();
        driver.findElement(By.id("controller_Connect_login_action_userCde")).clear();

        driver.findElement(By.id("controller_Connect_login_action_userCde")).sendKeys("admin");
        driver.findElement(By.id("controller_Connect_login_action_userPwd")).sendKeys("adminpass");

        driver.findElement(By.id("controller_Connect_login_action_submit")).click();

        // verification de la balise h1
        assertTrue(driver.findElement(By.xpath("//h1")).getText().equals("Tableau de bord - Gestionnaire"));




    }
}
